version: "3.9"
services:
  app:
    build: .
    ports:
     - "8000:80"
    volumes:
        - .:/var/www/html
    working_dir: /var/www/html
    container_name: events-management
    environment:
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
  mysql:
    image: mariadb:10.8.3
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events_management_app
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1